# Generated by Django 4.2.6 on 2024-04-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
